//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMSEntities : DbContext
    {
        public EMSEntities()
            : base("name=EMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AttendEvent> AttendEvents { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EmailAdmin> EmailAdmins { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<PersonVoted> PersonVoteds { get; set; }
        public virtual DbSet<TypeCustomer> TypeCustomers { get; set; }
        public virtual DbSet<VoteNew> VoteNews { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    }
}
